version: '2'

# web refer to the http proxy exteranl network
networks:
  web:
    external:
      name: haproxy_default

services:

  web:
    build:
      context: .
      args:
        - PROJECTNAME
        - WUID
        - WGID
    stop_signal: SIGINT 
    volumes:
      - '.:/home/webdev'
    networks:
      default:
      web:
        # for resolving this site hostname to the container ip use
#       aliases:
#          - 'example.tld'

